# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2025, Hewlett Packard Enterprise Development LP

#
# src/test/obj_ctl_pop_flush/Makefile -- build obj_ctl_pop_flush test
#
TARGET = obj_ctl_pop_flush
OBJS = obj_ctl_pop_flush.o

LIBPMEMOBJ=y

include ../Makefile.inc
