#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2015-2024, Intel Corporation

#
# src/test/obj_toid/TEST0 -- unit test for obj_toid
#

. ../_unittest/unittest.sh

require_test_type medium

setup

expect_normal_exit ./obj_toid$EXESUFFIX $DIR/testfile1

check

pass
