# Run the Bandit scanner for finding vulnerabilities in the python code.
name: Bandit

on: [push, pull_request, workflow_dispatch]

env:
  GITHUB_REPO:  pmem/pmdk
  DOCKER_REPO:  ghcr.io/pmem/pmdk
  HOST_WORKDIR: /home/runner/work/pmdk/pmdk
  WORKDIR:      utils/docker
  BANDIT:       1
  OS:           ubuntu
  OS_VER:       22.04

jobs:
  bandit:
    name: Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Pull or rebuild the image
        run: cd $WORKDIR && ./pull-or-rebuild-image.sh

      - name: Run the build
        run: cd $WORKDIR && ./build-CI.sh
